// DO NOT EDIT THIS FILE
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.net.URI;
import java.util.Arrays;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeUnit;
import java.util.function.Supplier;
import java.util.stream.Stream;
import javax.tools.DiagnosticCollector;
import javax.tools.SimpleJavaFileObject;
import javax.tools.ToolProvider;

/** A helper class to test CS2030S labs. */
class CS2030STest {

  private static final String ANSI_RESET = "\u001B[0m";
  private static final String ANSI_RED = "\u001B[31m";
  private static final String ANSI_GREEN = "\u001B[32m";

  public static Class<?> kelas(String name) {
    try {
      return Class.forName(name);
    } catch (ClassNotFoundException e) {
      return null;
    }
  }

  public static Object newInstance(String className, double i) {
    try {
      return Class.forName(className).getConstructor(double.class).newInstance(i);
    } catch (ClassNotFoundException e) {
      System.err.println("No such class: " + className);
      return null;
    } catch (ReflectiveOperationException e) {
      System.err.println(e);
      return null;
    }
  }

  public static Object newInstance(String className) {
    try {
      return Class.forName(className).getConstructor().newInstance();
    } catch (ClassNotFoundException e) {
      System.err.println("No such class: " + className);
      return null;
    } catch (ReflectiveOperationException e) {
      System.err.println(e);
      return null;
    }
  }

  public static Object newInstance(String name, int i) {
    try {
      return Class.forName(name).getConstructor(int.class).newInstance(i);
    } catch (ReflectiveOperationException e) {
      return null;
    }
  }

  public static Method method(String className, String methodName, Class<?>... parameterTypes) {
    try {
      return Class.forName(className).getDeclaredMethod(methodName, parameterTypes);
    } catch (ClassNotFoundException e) {
      return null;
    } catch (NoSuchMethodException e) {
      return null;
    }
  }

  public static Method superMethod(
      String className, String methodName, Class<?>... parameterTypes) {
    try {
      return Class.forName(className).getMethod(methodName, parameterTypes);
    } catch (ClassNotFoundException e) {
      return null;
    } catch (NoSuchMethodException e) {
      return null;
    }
  }

  public static Stream<Method> methods(String className) {
    try {
      return Arrays.stream(Class.forName(className).getDeclaredMethods());
    } catch (ClassNotFoundException e) {
      return Stream.of();
    }
  }

  public static Constructor<?> constructor(String className, Class<?>... parameterTypes) {
    try {
      return Class.forName(className).getDeclaredConstructor(parameterTypes);
    } catch (ClassNotFoundException e) {
      return null;
    } catch (NoSuchMethodException e) {
      return null;
    }
  }

  public static Stream<Constructor<?>> constructors(String className) {
    try {
      return Arrays.stream(Class.forName(className).getDeclaredConstructors());
    } catch (ClassNotFoundException e) {
      return Stream.of();
    }
  }

  public static Stream<Field> fields(String className) {
    try {
      return Arrays.stream(Class.forName(className).getDeclaredFields());
    } catch (ClassNotFoundException e) {
      return Stream.of();
    }
  }

  public static Field field(String className, String fieldName) {
    try {
      return Class.forName(className).getDeclaredField(fieldName);
    } catch (ClassNotFoundException e) {
      System.err.println("No such class: " + className);
      return null;
    } catch (NoSuchFieldException e) {
      System.err.println("No such field " + className + "." + fieldName);
      return null;
    }
  }

  private static void print_ok() {
    System.out.println(".. " + ANSI_GREEN + "ok" + ANSI_RESET);
  }

  private static void print_failure() {
    System.out.println(".. " + ANSI_RED + "failed" + ANSI_RESET);
  }

  /**
   * Test if two objects are equals.
   *
   * @param test A description of the test.
   * @param output The output from an expression.
   * @param expect The expected output from that expression.
   * @return this object.
   */
  public CS2030STest expect(String test, Object output, Object expect) {
    System.out.print(test);
    if ((expect == null && output != null) || (expect != null && output == null)) {
      print_failure();
      System.out.println("  expected: " + expect);
      System.out.println("  got this: " + output);
      return this;
    }

    if ((expect == null && output == null) || output.equals(expect)) {
      print_ok();
    } else {
      print_failure();
      System.out.println("  expected: " + expect);
      System.out.println("  got this: " + output);
    }
    return this;
  }

  public CS2030STest expect(String test, String output, String expect) {
    System.out.print(test);
    if ((expect == null && output == null)
        || output.replaceAll("\\s+", "").compareToIgnoreCase(expect.replaceAll("\\s+", "")) == 0) {
      print_ok();
    } else {
      print_failure();
      System.out.println("  expected: " + expect);
      System.out.println("  got this: " + output);
    }
    return this;
  }

  /**
   * @param <T> The type of object the given task will produce.
   * @param test A description of the test.
   * @param task The task to run.
   * @param expect The expected output from that expression.
   * @return this object.
   */
  public <T> CS2030STest expect(String test, Supplier<String> task, String expect) {
    try {
      String output = CompletableFuture.supplyAsync(task).get(5, TimeUnit.SECONDS);
      System.out.print(test);
      if ((expect == null && output != null) || (expect != null && output == null)) {
        print_failure();
        System.out.println("  expected: " + expect);
        System.out.println("  got this: " + output);
        return this;
      }

      if ((expect == null && output == null)
          || output.replaceAll("\\s+", "").compareToIgnoreCase(expect.replaceAll("\\s+", ""))
              == 0) {
        print_ok();
      } else {
        print_failure();
        System.out.println("  expected: " + expect);
        System.out.println("  got this: " + output);
      }
    } catch (Exception e) {
      System.out.print(test);
      print_failure();
      System.out.println("  with exception: " + e.getMessage());
      e.printStackTrace();
    }
    return this;
  }

  /**
   * @param <T> The type of object the given task will produce.
   * @param test A description of the test.
   * @param task The task to run.
   * @param expect The expected output from that expression.
   * @return this object.
   */
  public <T> CS2030STest expect(String test, Supplier<T> task, Object expect) {
    try {
      T output = CompletableFuture.supplyAsync(task).get(5, TimeUnit.SECONDS);
      System.out.print(test);
      if ((expect == null && output != null) || (expect != null && output == null)) {
        print_failure();
        System.out.println("  expected: " + expect);
        System.out.println("  got this: " + output);
        return this;
      }

      if ((expect == null && output == null) || output.equals(expect)) {
        print_ok();
      } else {
        print_failure();
        System.out.println("  expected: " + expect);
        System.out.println("  got this: " + output);
      }
    } catch (Exception e) {
      System.out.print(test);
      print_failure();
      System.out.println("  with exception: " + e.getMessage());
      e.printStackTrace();
    }
    return this;
  }

  public CS2030STest expectPrint(String test, Runnable task, String expect) {
    try {
      ByteArrayOutputStream baos = new ByteArrayOutputStream();
      final PrintStream old = System.out;
      System.setOut(new PrintStream(baos));
      CompletableFuture.runAsync(task).get(5, TimeUnit.SECONDS);
      System.out.flush();
      System.setOut(old);
      String output = baos.toString();

      System.out.print(test);
      if ((expect == null && output != null) || (expect != null && output == null)) {
        print_failure();
        System.out.println("  expected: " + expect);
        System.out.println("  got this: " + output);
        return this;
      }

      if ((expect == null && output == null) || output.equals(expect)) {
        print_ok();
      } else {
        print_failure();
        System.out.println("  expected: " + expect);
        System.out.println("  got this: " + output);
      }
    } catch (Exception e) {
      System.out.print(test);
      print_failure();
      System.out.println("  with exception: " + e.getMessage());
      e.printStackTrace();
    }
    return this;
  }

  /**
   * Test if a given producer returns a value. Wrapper around expect(..) to simplify caller.
   *
   * @param <T> The type of object the given task will produce.
   * @param test A description of the test.
   * @param task The task to run.
   * @param expect The expected output from that expression.
   * @return this object.
   */
  public <T> CS2030STest expectReturn(String test, Supplier<T> task, Object expect) {
    return this.expect(test + " returns " + expect, task, expect);
  }

  /**
   * Test if an expression throws an exception.
   *
   * @param test A description of the test.
   * @param task A lambda expression of the expression.
   * @param expectedE A exception instance of the same type as the expected one.
   * @return this object.
   */
  public CS2030STest expectException(String test, Runnable task, Exception expectedE) {
    boolean gotException = false;
    try {
      CompletableFuture.runAsync(task).get(5, TimeUnit.SECONDS);
    } catch (Exception e) {
      if (e.getClass().equals(expectedE.getClass())) {
        gotException = true;
      }
    }
    System.out.print(test);
    if (gotException) {
      print_ok();
    } else {
      print_failure();
    }
    return this;
  }

  public CS2030STest expectCheckedException(String test, Runnable task, Object expectedE) {
    boolean gotException = false;
    try {
      CompletableFuture.runAsync(task).get(5, TimeUnit.SECONDS);
    } catch (ExecutionException e) {
      if (e.getCause().getClass().equals(expectedE.getClass())) {
        gotException = true;
      }
    } catch (Throwable e) {
      // do nothing
    }
    System.out.print(test);
    if (gotException) {
      print_ok();
    } else {
      print_failure();
    }
    return this;
  }

  public CS2030STest expectCheckedExceptionMessage(
      String test, Runnable task, Exception expectedE) {
    boolean gotException = false;
    try {
      CompletableFuture.runAsync(task).get(5, TimeUnit.SECONDS);
    } catch (ExecutionException e) {
      if (e.getCause().getClass().equals(expectedE.getClass())
          && e.getCause().getMessage().equals(expectedE.getMessage())) {
        gotException = true;
      }
    } catch (Throwable e) {
      // do nothing
    }
    System.out.print(test);
    if (gotException) {
      print_ok();
    } else {
      print_failure();
      System.out.println("  did not catch expected exception " + expectedE.getClass());
      System.out.println("  did not match message " + expectedE.getMessage());
    }
    return this;
  }

  public CS2030STest expectCheckedExceptionMessage(
      String test, Runnable task, Class<?> expectedE, String expectedMsg) {
    boolean gotException = false;
    try {
      CompletableFuture.runAsync(task).get(5, TimeUnit.SECONDS);
    } catch (ExecutionException e) {
      if (e.getCause().getClass().equals(expectedE)
          && e.getCause().getMessage().equals(expectedMsg)) {
        gotException = true;
      }
    } catch (Throwable e) {
      // do nothing
    }
    System.out.print(test);
    if (gotException) {
      print_ok();
    } else {
      print_failure();
      System.out.println(
          "  did not catch expected exception " + expectedE + " with message " + expectedMsg);
    }
    return this;
  }

  /**
   * Test if an expression compiles with/without error.
   *
   * @param test A description of the test.
   * @param statement The java statement to compile
   * @param success Whether the statement is expected to compile or not (true if yes; false
   *     otherwise)
   * @return this object.
   */
  public CS2030STest expectCompile(String test, String statement, boolean success) {
    System.out.print(test);

    class JavaSourceFromString extends SimpleJavaFileObject {
      private final String code;

      public JavaSourceFromString(String code) {
        super(URI.create("string:///TempClass.java"), Kind.SOURCE);
        this.code = "class TempClass {void foo(){" + code + ";}}";
      }

      @Override
      public CharSequence getCharContent(boolean ignoreEncodingErrors) {
        return code;
      }
    }

    boolean noError =
        ToolProvider.getSystemJavaCompiler()
            .getTask(
                null,
                null,
                new DiagnosticCollector<>(),
                null,
                null,
                List.of(new JavaSourceFromString(statement)))
            .call();

    if (noError != success) {
      print_failure();
      if (!success) {
        System.out.println("  expected compilation error but it compiles fine.");
      } else {
        System.out.println("  expected the statement to compile without errors but it does not.");
      }
    } else {
      print_ok();
    }
    return this;
  }

  public CS2030STest expectIsException(String className) {
    return this.expect(
        className + " is an exception",
        () -> {
          try {
            return Exception.class.isAssignableFrom(Class.forName(className));
          } catch (ClassNotFoundException e) {
            return false;
          }
        },
        true);
  }

  public CS2030STest expectIsCheckedException(String className) {
    return this.expect(
        className + " is a checked exception",
        () -> {
          try {
            return !RuntimeException.class.isAssignableFrom(Class.forName(className));
          } catch (ClassNotFoundException e) {
            return false;
          }
        },
        true);
  }

  public CS2030STest expectHasConstructor(String className, Class<?>... paramTypes) {
    return this.expect(
        className + " correctly declares its construtor",
        () -> {
          try {
            return Arrays.stream(Class.forName(className).getDeclaredConstructors())
                .filter(c -> c.getParameterCount() == paramTypes.length)
                .filter(c -> Arrays.equals(c.getParameterTypes(), paramTypes))
                .filter(c -> Modifier.isPublic(c.getModifiers()))
                .findFirst()
                .isPresent();
          } catch (ClassNotFoundException e) {
            return false;
          }
        },
        true);
  }

  public CS2030STest expectNumOfMethods(String className, int count) {
    return this.expect(
        className + " has the expected number of non-private methods",
        () -> {
          try {
            return Arrays.stream(Class.forName(className).getDeclaredMethods())
                    .filter(c -> !Modifier.isPrivate(c.getModifiers()))
                    .count()
                == count;
          } catch (ClassNotFoundException e) {
            return false;
          }
        },
        true);
  }

  public CS2030STest expectIsAbstractClass(String className) {
    return this.expect(
        className + " is an abstract class",
        () -> {
          try {
            int m = Class.forName(className).getModifiers();
            return Modifier.isAbstract(m) && !Modifier.isInterface(m);
          } catch (ClassNotFoundException e) {
            return false;
          }
        },
        true);
  }

  public CS2030STest expectInstanceField(String className, Class<?> type, String fieldName) {
    return this.expect(
        className + " correctly declares the field " + fieldName,
        () -> {
          try {
            return Arrays.stream(Class.forName(className).getDeclaredFields())
                .filter(f -> f.getName().equals(fieldName))
                .filter(f -> f.getType().equals(type))
                .filter(f -> !Modifier.isStatic(f.getModifiers()))
                .filter(f -> Modifier.isPrivate(f.getModifiers()))
                .findFirst()
                .isPresent();
          } catch (ClassNotFoundException e) {
            return false;
          }
        },
        true);
  }

  public CS2030STest expectClassField(String className, Class<?> type, String fieldName) {
    return this.expect(
        className + " correctly declares the field " + fieldName,
        () -> {
          try {
            return Arrays.stream(Class.forName(className).getDeclaredFields())
                .filter(f -> f.getName().equals(fieldName))
                .filter(f -> f.getType().equals(type))
                .filter(f -> Modifier.isStatic(f.getModifiers()))
                .filter(f -> Modifier.isPrivate(f.getModifiers()))
                .findFirst()
                .isPresent();
          } catch (ClassNotFoundException e) {
            return false;
          }
        },
        true);
  }

  public CS2030STest expectUnchangedInstanceField(
      String className, Class<?> type, String fieldName) {
    return this.expect(
        className + " correctly declares the field " + fieldName,
        () -> {
          try {
            return Arrays.stream(Class.forName(className).getDeclaredFields())
                .filter(f -> f.getName().equals(fieldName))
                .filter(f -> f.getType().equals(type))
                .filter(f -> !Modifier.isStatic(f.getModifiers()))
                .filter(f -> Modifier.isFinal(f.getModifiers()))
                .filter(f -> Modifier.isPrivate(f.getModifiers()))
                .findFirst()
                .isPresent();
          } catch (ClassNotFoundException e) {
            return false;
          }
        },
        true);
  }

  public CS2030STest expectPublicConstantField(String className, Class<?> type, String fieldName) {
    return this.expect(
        className + " correctly declares the field " + fieldName,
        () -> {
          try {
            return Arrays.stream(Class.forName(className).getDeclaredFields())
                .filter(f -> f.getName().equals(fieldName))
                .filter(f -> f.getType().equals(type))
                .filter(f -> Modifier.isStatic(f.getModifiers()))
                .filter(f -> Modifier.isFinal(f.getModifiers()))
                .filter(f -> Modifier.isPublic(f.getModifiers()))
                .findFirst()
                .isPresent();
          } catch (ClassNotFoundException e) {
            return false;
          }
        },
        true);
  }

  public CS2030STest expectConstantField(String className, Class<?> type, String fieldName) {
    return this.expect(
        className + " correctly declares the field " + fieldName,
        () -> {
          try {
            return Arrays.stream(Class.forName(className).getDeclaredFields())
                .filter(f -> f.getName().equals(fieldName))
                .filter(f -> f.getType().equals(type))
                .filter(f -> Modifier.isStatic(f.getModifiers()))
                .filter(f -> Modifier.isFinal(f.getModifiers()))
                .findFirst()
                .isPresent();
          } catch (ClassNotFoundException e) {
            return false;
          }
        },
        true);
  }

  public CS2030STest expectAbstractMethod(
      String className, Class<?> returnType, String methodName, Class<?>... paramTypes) {
    return this.expect(
        className + " correctly declares the abstract method " + methodName,
        () -> {
          try {
            return Arrays.stream(Class.forName(className).getDeclaredMethods())
                .filter(m -> m.getName().equals(methodName))
                .filter(m -> m.getReturnType().equals(returnType))
                .filter(m -> Modifier.isAbstract(m.getModifiers()))
                .filter(m -> Modifier.isPublic(m.getModifiers()))
                .filter(m -> !Modifier.isStatic(m.getModifiers()))
                .filter(m -> Arrays.equals(m.getParameterTypes(), paramTypes))
                .findFirst()
                .isPresent();
          } catch (ClassNotFoundException e) {
            return false;
          }
        },
        true);
  }

  public CS2030STest expectInstanceMethod(
      String className, Class<?> returnType, String methodName, Class<?>... paramTypes) {
    return this.expect(
        className + " correctly declares the instance method " + methodName,
        () -> {
          try {
            return Arrays.stream(Class.forName(className).getDeclaredMethods())
                .filter(m -> m.getName().equals(methodName))
                .filter(m -> m.getReturnType().equals(returnType))
                .filter(m -> !Modifier.isAbstract(m.getModifiers()))
                .filter(m -> Modifier.isPublic(m.getModifiers()))
                .filter(m -> !Modifier.isStatic(m.getModifiers()))
                .filter(m -> Arrays.equals(m.getParameterTypes(), paramTypes))
                .findFirst()
                .isPresent();
          } catch (ClassNotFoundException e) {
            return false;
          }
        },
        true);
  }

  public CS2030STest expectClassMethod(
      String className, Class<?> returnType, String methodName, Class<?>... paramTypes) {
    return this.expect(
        className + " correctly declares the class method " + methodName,
        () -> {
          try {
            return Arrays.stream(Class.forName(className).getDeclaredMethods())
                .filter(m -> m.getName().equals(methodName))
                .filter(m -> m.getReturnType().equals(returnType))
                .filter(m -> !Modifier.isAbstract(m.getModifiers()))
                .filter(m -> Modifier.isPublic(m.getModifiers()))
                .filter(m -> Modifier.isStatic(m.getModifiers()))
                .filter(m -> Arrays.equals(m.getParameterTypes(), paramTypes))
                .findFirst()
                .isPresent();
          } catch (ClassNotFoundException e) {
            return false;
          }
        },
        true);
  }

  public CS2030STest expectMethodThrowsException(
      String className, String methodName, Class<?> exceptionType, Class<?>... paramTypes) {
    return this.expect(
        className + "::" + methodName + " may throw " + exceptionType.getName(),
        () -> {
          try {
            return Arrays.stream(
                    Class.forName(className)
                        .getDeclaredMethod(methodName, paramTypes)
                        .getExceptionTypes())
                .anyMatch(e -> e.equals(exceptionType));
          } catch (ClassNotFoundException e) {
            return false;
          } catch (NoSuchMethodException e) {
            return false;
          }
        },
        true);
  }

  public CS2030STest expectIsInterface(String className) {
    return this.expect(
        className + " is an interface",
        () -> {
          try {
            return Class.forName(className).isInterface();
          } catch (ClassNotFoundException e) {
            return false;
          }
        },
        true);
  }

  public CS2030STest expectIsSubclassOf(String className, String parentClassName) {
    return this.expect(
        className + " is a subclass of " + parentClassName,
        () -> {
          try {
            return Class.forName(className).getSuperclass().equals(Class.forName(parentClassName));
          } catch (ClassNotFoundException e) {
            return false;
          }
        },
        true);
  }

  public CS2030STest expectImplements(String className, String interfaceName) {
    return this.expect(
        className + " implements " + interfaceName,
        () -> {
          try {
            Class<?> i = Class.forName(interfaceName);
            return Arrays.stream(Class.forName(className).getInterfaces())
                .anyMatch(x -> x.equals(i));
          } catch (ClassNotFoundException e) {
            return false;
          }
        },
        true);
  }

  public CS2030STest expectOverrideAnnotation(
      String className, String methodName, Class<?>... paramTypes) {
    return this.expect(
        className + "::" + methodName + " has @Override annotation",
        () -> {
          try {
            return CS2030STest.method(className, methodName, paramTypes)
                .isAnnotationPresent(Override.class);
          } catch (NullPointerException e) {
            return false;
          }
        },
        true);
  }
}

@SuppressWarnings({"checkstyle:OneTopLevelClass", "checkstyle:TypeName"})
class $Class {
  public Object o;

  public $Class(String name) {
    String className = name;
    try {
      Constructor<?> c = null;
      try {
        c = Class.forName(className).getDeclaredConstructor();
      } catch (NoSuchMethodException e) {
        // do nothing
      }
      if (c == null) {
        c = Class.forName(className).getConstructor();
      }
      c.setAccessible(true);
      this.o = c.newInstance();
    } catch (ClassNotFoundException e) {
      System.err.println("No such class: " + className);
    } catch (ReflectiveOperationException e) {
      System.err.println(e);
    }
  }

  public $Class(String name, double d) {
    String className = name;
    try {
      Constructor<?> c = Class.forName(className).getDeclaredConstructor(double.class);
      c.setAccessible(true);
      this.o = c.newInstance(d);
    } catch (ClassNotFoundException e) {
      System.err.println("No such class: " + className);
    } catch (ReflectiveOperationException e) {
      System.err.println(e);
    }
  }

  public $Class(String name, String s) {
    String className = name;
    try {
      Constructor<?> c = Class.forName(className).getDeclaredConstructor(String.class);
      c.setAccessible(true);
      this.o = c.newInstance(s);
    } catch (ClassNotFoundException e) {
      System.err.println("No such class: " + className);
    } catch (ReflectiveOperationException e) {
      System.err.println(e);
    }
  }

  public $Class(String name, String s1, String s2) {
    String className = name;
    try {
      Constructor<?> c =
          Class.forName(className).getDeclaredConstructor(String.class, String.class);
      c.setAccessible(true);
      this.o = c.newInstance(s1, s2);
    } catch (ClassNotFoundException e) {
      System.err.println("No such class: " + className);
    } catch (ReflectiveOperationException e) {
      System.err.println(e);
    }
  }

  public $Class(String name, String s1, int x) {
    String className = name;
    try {
      Constructor<?> c = Class.forName(className).getDeclaredConstructor(String.class, int.class);
      c.setAccessible(true);
      this.o = c.newInstance(s1, x);
    } catch (ClassNotFoundException e) {
      System.err.println("No such class: " + className);
    } catch (ReflectiveOperationException e) {
      System.err.println(e);
    }
  }

  public $Class(String name, String s1, String s2, int x) {
    String className = name;
    try {
      Constructor<?> c =
          Class.forName(className).getDeclaredConstructor(String.class, String.class, int.class);
      c.setAccessible(true);
      this.o = c.newInstance(s1, s2, x);
    } catch (ClassNotFoundException e) {
      System.err.println("No such class: " + className);
    } catch (ReflectiveOperationException e) {
      System.err.println(e);
    }
  }

  public $Class(String name, int i) {
    String className = name;
    try {
      Constructor<?> c = Class.forName(className).getDeclaredConstructor(int.class);
      c.setAccessible(true);
      this.o = c.newInstance(i);
    } catch (ClassNotFoundException e) {
      System.err.println("No such class: " + className);
    } catch (ReflectiveOperationException e) {
      System.err.println(e);
    }
  }

  public $Class(String name, int i, double d) {
    String className = name;
    try {
      Constructor<?> c = Class.forName(className).getDeclaredConstructor(int.class, double.class);
      c.setAccessible(true);
      this.o = c.newInstance(i, d);
    } catch (ClassNotFoundException e) {
      System.err.println("No such class: " + className);
    } catch (ReflectiveOperationException e) {
      System.err.println(e);
    }
  }

  public $Class(String name, int i, int j) {
    String className = name;
    try {
      Constructor<?> c = Class.forName(className).getDeclaredConstructor(int.class, int.class);
      c.setAccessible(true);
      this.o = c.newInstance(i, j);
    } catch (ClassNotFoundException e) {
      System.err.println("No such class: " + className);
    } catch (ReflectiveOperationException e) {
      System.err.println(e);
    }
  }

  public $Class(String name, double d, String s) {
    String className = name;
    try {
      Constructor<?> c =
          Class.forName(className).getDeclaredConstructor(double.class, String.class);
      c.setAccessible(true);
      this.o = c.newInstance(d, s);
    } catch (ClassNotFoundException e) {
      System.err.println("No such class: " + className);
    } catch (ReflectiveOperationException e) {
      System.err.println(e);
    }
  }

  public $Class(String name, Class<?> kelas, Object obj) {
    String className = name;
    try {
      Constructor<?> c = Class.forName(className).getDeclaredConstructor(kelas);
      c.setAccessible(true);
      this.o = c.newInstance(obj);
    } catch (ClassNotFoundException e) {
      System.err.println("No such class: " + className);
    } catch (ReflectiveOperationException e) {
      System.err.println(e);
    }
  }

  public $Class(String name, Class<?> kelas, Object obj, double d) {
    String className = name;
    try {
      Constructor<?> c = Class.forName(className).getDeclaredConstructor(kelas, double.class);
      c.setAccessible(true);
      this.o = c.newInstance(obj, d);
    } catch (ClassNotFoundException e) {
      System.err.println("No such class: " + className);
    } catch (ReflectiveOperationException e) {
      System.err.println(e);
    }
  }

  public $Class(String name, Class<?> kelas, Object obj, int i) {
    String className = name;
    try {
      Constructor<?> c = Class.forName(className).getDeclaredConstructor(kelas, int.class);
      c.setAccessible(true);
      this.o = c.newInstance(obj, i);
    } catch (ClassNotFoundException e) {
      System.err.println("No such class: " + className);
    } catch (ReflectiveOperationException e) {
      System.err.println(e);
    }
  }

  public $Class(String name, Class<?> kelas, Object obj, int i, double d) {
    String className = name;
    try {
      Constructor<?> c =
          Class.forName(className).getDeclaredConstructor(kelas, int.class, double.class);
      c.setAccessible(true);
      this.o = c.newInstance(obj, i, d);
    } catch (ClassNotFoundException e) {
      System.err.println("No such class: " + className);
    } catch (ReflectiveOperationException e) {
      System.err.println(e);
    }
  }

  public $Class(String name, double d, String s, int i) {
    String className = name;
    try {
      Constructor<?> c =
          Class.forName(className).getDeclaredConstructor(double.class, String.class, int.class);
      c.setAccessible(true);
      this.o = c.newInstance(d, s, i);
    } catch (ClassNotFoundException e) {
      System.err.println("No such class: " + className);
    } catch (ReflectiveOperationException e) {
      System.err.println(e);
    }
  }

  public void call(String className, String methodName) throws ReflectiveOperationException {
    Method m = CS2030STest.method(className, methodName);
    m.setAccessible(true);
    m.invoke(o);
  }

  public void call(String className, String methodName, int i) throws ReflectiveOperationException {
    Method m = CS2030STest.method(className, methodName, int.class);
    m.setAccessible(true);
    m.invoke(o, i);
  }

  public void call(String className, String methodName, double d)
      throws ReflectiveOperationException {
    Method m = CS2030STest.method(className, methodName, double.class);
    m.setAccessible(true);
    m.invoke(o, d);
  }

  public void call(String className, String methodName, boolean b)
      throws ReflectiveOperationException {
    Method m = CS2030STest.method(className, methodName, boolean.class);
    m.setAccessible(true);
    m.invoke(o, b);
  }

  public void call(String className, String methodName, String s1, String s2)
      throws ReflectiveOperationException {
    Method m = CS2030STest.method(className, methodName, String.class, String.class);
    m.setAccessible(true);
    m.invoke(o, s1, s2);
  }

  public void call(String className, String methodName, Class<?> c, Object arg)
      throws ReflectiveOperationException {
    Method m = CS2030STest.method(className, methodName, c);
    m.setAccessible(true);
    m.invoke(o, arg);
  }

  public Object callWithReturn(String className, String methodName, double d)
      throws ReflectiveOperationException {
    Method m = CS2030STest.method(className, methodName, double.class);
    m.setAccessible(true);
    return m.invoke(o, d);
  }

  public Object callWithReturn(String className, String methodName, int d)
      throws ReflectiveOperationException {
    Method m = CS2030STest.method(className, methodName, int.class);
    m.setAccessible(true);
    return m.invoke(o, d);
  }

  public Object callWithReturn(String className, String methodName)
      throws ReflectiveOperationException {
    Method m = CS2030STest.method(className, methodName);
    m.setAccessible(true);
    return m.invoke(o);
  }

  public Object callWithReturn(String className, String methodName, Class<?> c, Object arg)
      throws ReflectiveOperationException {
    Method m = CS2030STest.method(className, methodName, c);
    m.setAccessible(true);
    return m.invoke(o, arg);
  }

  public Object callSuperWithReturn(String className, String methodName)
      throws ReflectiveOperationException {
    Method m = CS2030STest.superMethod(className, methodName);
    m.setAccessible(true);
    return m.invoke(o);
  }

  public Object get(String fieldName) throws ReflectiveOperationException {
    return CS2030STest.field(o.getClass().getName(), fieldName).get(o);
  }

  @Override
  public String toString() {
    return o.toString();
  }
}

@SuppressWarnings({"checkstyle:OneTopLevelClass", "checkstyle:TypeName"})
class $TourGuide extends $Class {
  public $TourGuide(int id) {
    super("TourGuide", id);
  }
}

@SuppressWarnings({"checkstyle:OneTopLevelClass", "checkstyle:TypeName"})
class $Visitor extends $Class {
  public $Visitor(int i) {
    super("Visitor", i);
  }

  public int getTicketType() throws ReflectiveOperationException {
    return (int) callWithReturn("Visitor", "getTicketType");
  }
}

@SuppressWarnings({"checkstyle:OneTopLevelClass", "checkstyle:TypeName"})
class $VisitorQueue extends $Class {
  public $VisitorQueue(int i, int j) {
    super("VisitorQueue", i, j);
  }

  public boolean enq($Visitor t) throws ReflectiveOperationException {
    return (Boolean) callWithReturn("VisitorQueue", "enq", CS2030STest.kelas("Visitor"), t.o);
  }

  public int compareTo($VisitorQueue q) throws ReflectiveOperationException {
    return (Integer)
        callWithReturn("VisitorQueue", "compareTo", CS2030STest.kelas("VisitorQueue"), q.o);
  }
}

@SuppressWarnings({"checkstyle:OneTopLevelClass", "checkstyle:TypeName"})
class $VisitorCentre extends $Class {
  public $VisitorCentre(int i, int j) {
    super("VisitorCentre", i, j);
  }

  public static Object getStatic(String fieldName) throws ReflectiveOperationException {
    return CS2030STest.field("VisitorCentre", fieldName).get(null);
  }

  public void welcome($Visitor v) throws InvocationTargetException, ReflectiveOperationException {
    call("VisitorCentre", "welcome", CS2030STest.kelas("Visitor"), v.o);
  }

  public Object admitToAttraction() throws ReflectiveOperationException {
    return callWithReturn("VisitorCentre", "admitToAttraction");
  }
}
