// DO NOT EDIT THIS FILE
import java.lang.reflect.InvocationTargetException;

class Test4 {
  public static void main(String[] args) {
    CS2030STest we = new CS2030STest();

    we.expectHasConstructor("VisitorCentre", int.class, int.class);
    we.expectInstanceMethod(
        "VisitorCentre", we.kelas("VisitorCentre"), "welcome", we.kelas("Visitor"));
    we.expectMethodThrowsException(
        "VisitorCentre", "admitToAttraction", AttractionFullException.class);
    we.expectInstanceMethod("VisitorCentre", we.kelas("Visitor"), "admitToAttraction");
    we.expectInstanceMethod("VisitorCentre", String.class, "toString");
    we.expectOverrideAnnotation("VisitorCentre", "toString");

    $VisitorCentre vc = new $VisitorCentre(2, 3);

    we.expect(
        "VisitorCentre correctly defines constant EXPRESS",
        () -> {
          try {
            return $VisitorCentre.getStatic("EXPRESS");
          } catch (ReflectiveOperationException e) {
            return -1;
          }
        },
        2);
    we.expect(
        "VisitorCentre correctly defines constant REGULAR",
        () -> {
          try {
            return $VisitorCentre.getStatic("REGULAR");
          } catch (ReflectiveOperationException e) {
            return -1;
          }
        },
        1);
    we.expect(
        "VisitorCentre correctly defines constant WALKIN",
        () -> {
          try {
            return $VisitorCentre.getStatic("WALKIN");
          } catch (ReflectiveOperationException e) {
            return -1;
          }
        },
        0);

    we.expect(
        "VisitorCentre::toString returns the correct string",
        vc.toString(),
        "VC: [ 0:Q0 [ ], 1:Q1 [ ], 2:Q2 [ ] ]");

    we.expect(
        "VisitorCentre correctly returns null when there is no visitor",
        () -> {
          try {
            return vc.admitToAttraction();
          } catch (InvocationTargetException e) {
            return e.getCause().getMessage();
          } catch (ReflectiveOperationException e) {
            return "";
          }
        },
        null);

    we.expect(
        "VisitorCentre accepts visitor in an appropriate queue",
        () -> {
          try {
            vc.welcome(new $Visitor(0));
            return vc.toString();
          } catch (ReflectiveOperationException e) {
            return "";
          }
        },
        "VC: [ 0:Q0 [ V1000 ], 1:Q1 [ ], 2:Q2 [ ] ]");

    we.expect(
        "VisitorCentre correctly accepts visitor into a queue",
        () -> {
          try {
            vc.welcome(new $Visitor(2));
            return vc.toString();
          } catch (ReflectiveOperationException e) {
            return "";
          }
        },
        "VC: [ 0:Q0 [ V1000 ], 1:Q1 [ ], 2:Q2 [ V1001 ] ]");

    we.expect(
        "VisitorCentre correctly admits the next visitor to attraction",
        () -> {
          try {
            return vc.admitToAttraction().toString();
          } catch (InvocationTargetException e) {
            return "";
          } catch (ReflectiveOperationException e) {
            return "";
          }
        },
        "V1001");

    we.expect(
        "VisitorCentre correctly accepts visitor into a queue",
        () -> {
          try {
            vc.welcome(new $Visitor(0));
            return vc.toString();
          } catch (ReflectiveOperationException e) {
            return "";
          }
        },
        "VC: [ 0:Q0 [ V1000 V1002 ], 1:Q1 [ ], 2:Q2 [ ] ]");

    we.expect(
        "VisitorCentre correctly ignores visitor when a queue is full",
        () -> {
          try {
            vc.welcome(new $Visitor(0));
            return vc.toString();
          } catch (ReflectiveOperationException e) {
            return "";
          }
        },
        "VC: [ 0:Q0 [ V1000 V1002 ], 1:Q1 [ ], 2:Q2 [ ] ]");

    we.expect(
        "VisitorCentre correctly accepts visitor into a queue",
        () -> {
          try {
            vc.welcome(new $Visitor(1));
            return vc.toString();
          } catch (ReflectiveOperationException e) {
            return "";
          }
        },
        "VC: [ 0:Q0 [ V1000 V1002 ], 1:Q1 [ V1004 ], 2:Q2 [ ] ]");

    we.expect(
        "VisitorCentre correctly admits the next visitor into the attraction",
        () -> {
          try {
            return vc.admitToAttraction().toString();
          } catch (InvocationTargetException e) {
            return "";
          } catch (ReflectiveOperationException e) {
            return "";
          }
        },
        "V1004");

    we.expect(
        "VisitorCentre correctly admits the next visitor into the attraction",
        () -> {
          try {
            return vc.admitToAttraction().toString();
          } catch (InvocationTargetException e) {
            return "";
          } catch (ReflectiveOperationException e) {
            return "";
          }
        },
        "V1000");

    we.expect(
        "VisitorCentre correctly throws AttractionFullException",
        () -> {
          try {
            vc.admitToAttraction();
            return false;
          } catch (InvocationTargetException e) {
            return e.getCause().getClass().equals(AttractionFullException.class);
          } catch (ReflectiveOperationException e) {
            return false;
          }
        },
        true);

    we.expect(
        "VisitorCentre correctly throws AttractionFullException with the right message",
        () -> {
          try {
            vc.admitToAttraction();
            return "";
          } catch (InvocationTargetException e) {
            return e.getCause().getMessage();
          } catch (ReflectiveOperationException e) {
            return "";
          }
        },
        "Attraction capacity of 3 reached.");
  }
}
