// DO NOT EDIT THIS FILE
class Test1 {
  public static void main(String[] args) {
    CS2030STest we = new CS2030STest();

    we.expectHasConstructor("TourGuide", int.class);
    we.expectUnchangedInstanceField("TourGuide", int.class, "id");
    we.expectInstanceMethod("TourGuide", String.class, "toString");
    we.expectOverrideAnnotation("TourGuide", "toString");

    we.expect(
        "TourGuide::toString returns the correct string representation",
        () -> new $TourGuide(123).toString(),
        "TG123");
  }
}
