// DO NOT EDIT THIS FILE

class Test2 {
  public static void main(String[] args) {
    CS2030STest we = new CS2030STest();

    we.expectHasConstructor("Visitor", int.class);
    we.expectUnchangedInstanceField("Visitor", int.class, "id");
    we.expectInstanceMethod("Visitor", int.class, "getTicketType");
    we.expectInstanceMethod("Visitor", String.class, "toString");
    we.expectOverrideAnnotation("Visitor", "toString");

    we.expect(
        "Visitor::toString returns the correct string representation",
        () -> new $Visitor(0).toString(),
        "V1000");

    we.expect("Visitor correctly increments IDs", () -> new $Visitor(0).toString(), "V1001");

    we.expect(
        "Visitor::getTicketType correctly returns ticket type",
        () -> {
          try {
            return new $Visitor(1).getTicketType();
          } catch (ReflectiveOperationException e) {
            return 0;
          }
        },
        1);
  }
}
