// DO NOT EDIT THIS FILE
class Test3 {
  public static void main(String[] args) {
    CS2030STest we = new CS2030STest();

    we.expectIsSubclassOf("VisitorQueue", "Queue");
    we.expectImplements("VisitorQueue", "java.lang.Comparable");
    we.expectUnchangedInstanceField("VisitorQueue", int.class, "id");
    we.expectHasConstructor("VisitorQueue", int.class, int.class);
    we.expectInstanceMethod("VisitorQueue", boolean.class, "enq", we.kelas("Visitor"));
    we.expectOverrideAnnotation("VisitorQueue", "enq", we.kelas("Visitor"));
    we.expectInstanceMethod("VisitorQueue", int.class, "compareTo", we.kelas("VisitorQueue"));
    we.expectOverrideAnnotation("VisitorQueue", "compareTo", we.kelas("VisitorQueue"));

    $VisitorQueue q1 = new $VisitorQueue(0, 2);
    $VisitorQueue q2 = new $VisitorQueue(1, 1);
    $VisitorQueue q3 = new $VisitorQueue(0, 1);

    we.expect("VisitorQueue::toString returns the correct string", () -> q1.toString(), "Q0 [ ]");

    we.expect(
        "VisitorQueue correctly accepts visitor if queue is not full",
        () -> {
          try {
            return q1.enq(new $Visitor(0));
          } catch (ReflectiveOperationException e) {
            return false;
          }
        },
        true);

    we.expect(
        "VisitorQueue only accepts visitor of same id",
        () -> {
          try {
            return q1.enq(new $Visitor(1));
          } catch (ReflectiveOperationException e) {
            return true;
          }
        },
        false);

    we.expect(
        "VisitorQueue::toString returns correct string with visitors",
        () -> {
          try {
            q1.enq(new $Visitor(0));
            return q1.toString();
          } catch (ReflectiveOperationException e) {
            return "";
          }
        },
        "Q0 [ V1000 V1002 ]");

    we.expect(
        "VisitorQueue correctly rejects visitors if queue is full",
        () -> {
          try {
            return q1.enq(new $Visitor(0));
          } catch (ReflectiveOperationException e) {
            return true;
          }
        },
        false);

    we.expect(
        "VisitorQueue correctly compares empty queue",
        () -> {
          try {
            return q2.compareTo(q1);
          } catch (ReflectiveOperationException e) {
            return 0;
          }
        },
        -1);

    we.expect(
        "VisitorQueue correctly compares queue when ids are different",
        () -> {
          try {
            q2.enq(new $Visitor(1));
            return q2.compareTo(q1);
          } catch (ReflectiveOperationException e) {
            return 0;
          }
        },
        1);

    we.expect(
        "VisitorQueue correctly compares queue when ids are same",
        () -> {
          try {
            return q3.compareTo(q1);
          } catch (ReflectiveOperationException e) {
            return 0;
          }
        },
        -1);

    we.expect(
        "VisitorQueue correctly compares queue when ids are same",
        () -> {
          try {
            q3.enq(new $Visitor(0));
            return q3.compareTo(q1);
          } catch (ReflectiveOperationException e) {
            return 0;
          }
        },
        -1);
  }
}
